---
version: "3.7"
services:

  client:
    image: kahoot-clone-client:latest
    container_name: kahoot-client
    build: ./client
    ports:
    - 4200:4200
    networks:
    - internal
    - web
    depends_on:
    - server

  server:
    image: kahoot-clone-server:latest
    container_name: kahoot-server
    build: ./server
    ports:
    - 8083:8083
    depends_on:
    - mongodb
    volumes:
    - ./server/config/default.json:/app/config/default.json
    links:
    - mongodb:mongodb
    networks:
    - internal

  mongodb:
    image: webhippie/mongodb:latest
    container_name: kahoot-mongodb
    ports:
    - 27017:27017
    - 28017:28017
    - 27019:27019
    volumes:
    - mongo-data:/var/lib/mongodb/db
    - mongo-backup:/var/lib/backup
    networks:
    - internal
    environment:
    - MONGODB_AUTH=${MONGODB_AUTH}
    - MONGODB_AUTH_DB=${MONGODB_AUTH_DB}
    - MONGODB_DATABASE=${MONGODB_DATABASE}
    - MONGODB_DBPATH=${MONGODB_DBPATH}
    - MONGODB_PASSWORD=${MONGODB_PASSWORD}
    - MONGODB_REST=${MONGODB_REST}
    - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    - MONGODB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
    - MONGODB_USERNAME=${MONGODB_USERNAME}
    - MONGODB_VERBOSE=${MONGODB_VERBOSE}

  # mongoexpress:

volumes:
  mongo-data:
  mongo-backup:

networks:
  internal:
  web:
    external: true
