---
version: "3.7"
services:

  client:
    image: kahoot-clone-client:latest
    container_name: kahoot-client
    build: ./client
    ports:
    - 4200:4200
    - 9876:9876
    networks:
    - internal
    - web

  server:
    image: kahoot-clone-server:latest
    container_name: kahoot-server
    build: ./server
    ports:
    - 8080:8080
    depends_on:
    - mongodb
    volumes:
    - ./server/config/default.json:/app/config/default.json
    links:
    - mongodb:mongodb
    networks:
    - internal
    - web

  mongodb:
    image: webhippie/mongodb:latest
    container_name: kahoot-mongodb
    # build: .docker/mongodb-alpine
    ports:
    - 27017:27017
    - 28017:28017
    - 27019:27019
    volumes:
    - mongo-data:/var/lib/mongodb/db
    - mongo-backup:/var/lib/backup
    networks:
    - internal
    environment:
    - MONGODB_AUTH=${MONGODB_AUTH}
    - MONGODB_AUTH_DB=${MONGODB_AUTH_DB}
    - MONGODB_CLUSTER_AUTH_MODE=${MONGODB_CLUSTER_AUTH_MODE}
    - MONGODB_CONFIG=${MONGODB_CONFIG}
    - MONGODB_CONFIGSVR=${MONGODB_CONFIGSVR}
    - MONGODB_CPU=${MONGODB_CPU}
    - MONGODB_DATABASE=${MONGODB_DATABASE}
    - MONGODB_DBPATH=${MONGODB_DBPATH}
    - MONGODB_DIRECTORYPERDB=${MONGODB_DIRECTORYPERDB}
    - MONGODB_ENABLE_MAJORITY_READ_CONCERN=${MONGODB_ENABLE_MAJORITY_READ_CONCERN}
    - MONGODB_HTTPINTERFACE=${MONGODB_HTTPINTERFACE}
    - MONGODB_IPV6=${MONGODB_IPV6}
    - MONGODB_JOURNAL_COMMIT_INTERVAL=${MONGODB_JOURNAL_COMMIT_INTERVAL}
    - MONGODB_JOURNAL_OPTIONS=${MONGODB_JOURNAL_OPTIONS}
    - MONGODB_JSONP=${MONGODB_JSONP}
    - MONGODB_KEY_FILE=${MONGODB_KEY_FILE}
    - MONGODB_MAX_CONNS=${MONGODB_MAX_CONNS}
    - MONGODB_NETWORK_MESSAGE_COMPRESSORS=${MONGODB_NETWORK_MESSAGE_COMPRESSORS}
    - MONGODB_NOAUTH=${MONGODB_NOAUTH}
    - MONGODB_NOJOURNAL=${MONGODB_NOJOURNAL}
    - MONGODB_NOPREALLOC=${MONGODB_NOPREALLOC}
    - MONGODB_NOSCRIPTING=${MONGODB_NOSCRIPTING}
    - MONGODB_NOTABLESCAN=${MONGODB_NOTABLESCAN}
    - MONGODB_NO_INDEX_BUILD_RETRY=${MONGODB_NO_INDEX_BUILD_RETRY}
    - MONGODB_NSSIZE=${MONGODB_NSSIZE}
    - MONGODB_OPLOG_SIZE=${MONGODB_OPLOG_SIZE}
    - MONGODB_PASSWORD=${MONGODB_PASSWORD}
    - MONGODB_PERFORM_REPAIR=${MONGODB_PERFORM_REPAIR}
    - MONGODB_PERFORM_UPGRADE=${MONGODB_PERFORM_UPGRADE}
    - MONGODB_PROFILE=${MONGODB_PROFILE}
    - MONGODB_QUIET=${MONGODB_QUIET}
    - MONGODB_QUOTA=${MONGODB_QUOTA}
    - MONGODB_QUOTA_FILES=${MONGODB_QUOTA_FILES}
    - MONGODB_REPAIRPATH=${MONGODB_REPAIRPATH}
    - MONGODB_REPL_INDEX_PREFETCH=${MONGODB_REPL_INDEX_PREFETCH}
    - MONGODB_REPL_SET=${MONGODB_REPL_SET}
    - MONGODB_REST=${MONGODB_REST}
    - MONGODB_ROOT_PASSWORD=${MONGODB_ROOT_PASSWORD}
    - MONGODB_ROOT_USERNAME=${MONGODB_ROOT_USERNAME}
    - MONGODB_SET_PARAMETER=${MONGODB_SET_PARAMETER}
    - MONGODB_SHARDSVR=${MONGODB_SHARDSVR}
    - MONGODB_SLOWMS=${MONGODB_SLOWMS}
    - MONGODB_SMALLFILES=${MONGODB_SMALLFILES}
    - MONGODB_SSL_ALLOW_CONNECTIONS_WITHOUT_CERTIFICATES=${MONGODB_SSL_ALLOW_CONNECTIONS_WITHOUT_CERTIFICATES}
    - MONGODB_SSL_ALLOW_INVALID_CERTIFICATES=${MONGODB_SSL_ALLOW_INVALID_CERTIFICATES}
    - MONGODB_SSL_ALLOW_INVALID_HOSTNAMES=${MONGODB_SSL_ALLOW_INVALID_HOSTNAMES}
    - MONGODB_SSL_CA_FILE=${MONGODB_SSL_CA_FILE}
    - MONGODB_SSL_CLUSTER_FILE=${MONGODB_SSL_CLUSTER_FILE}
    - MONGODB_SSL_CLUSTER_PASSWORD=${MONGODB_SSL_CLUSTER_PASSWORD}
    - MONGODB_SSL_CRL_FILE=${MONGODB_SSL_CRL_FILE}
    - MONGODB_SSL_DISABLED_PROTOCOLS=${MONGODB_SSL_DISABLED_PROTOCOLS}
    - MONGODB_SSL_FIPS_MODE=${MONGODB_SSL_FIPS_MODE}
    - MONGODB_SSL_MODE=${MONGODB_SSL_MODE}
    - MONGODB_SSL_ON_NORMAL_PORTS=${MONGODB_SSL_ON_NORMAL_PORTS}
    - MONGODB_SSL_PEM_KEY_FILE=${MONGODB_SSL_PEM_KEY_FILE}
    - MONGODB_SSL_PEM_KEY_PASSWORD=${MONGODB_SSL_PEM_KEY_PASSWORD}
    - MONGODB_SSL_WEAK_CERTIFICATE_VALIDATION=${MONGODB_SSL_WEAK_CERTIFICATE_VALIDATION}
    - MONGODB_STORAGE_ENGINE=${MONGODB_STORAGE_ENGINE}
    - MONGODB_SYNCDELAY=${MONGODB_SYNCDELAY}
    - MONGODB_TIMESTAMP_FORMAT=${MONGODB_TIMESTAMP_FORMAT}
    - MONGODB_TRANSITION_TO_AUTH=${MONGODB_TRANSITION_TO_AUTH}
    - MONGODB_USERNAME=${MONGODB_USERNAME}
    - MONGODB_VERBOSE=${MONGODB_VERBOSE}
    - MONGODB_WIRED_TIGER_CACHE_SIZE=${MONGODB_WIRED_TIGER_CACHE_SIZE}
    - MONGODB_WIRED_TIGER_COLLECTION_BLOCK_COMPRESSOR=${MONGODB_WIRED_TIGER_COLLECTION_BLOCK_COMPRESSOR}
    - MONGODB_WIRED_TIGER_DIRECTORY_FOR_INDEXES=${MONGODB_WIRED_TIGER_DIRECTORY_FOR_INDEXES}
    - MONGODB_WIRED_TIGER_INDEX_PREFIX_COMPRESSION=${MONGODB_WIRED_TIGER_INDEX_PREFIX_COMPRESSION}
    - MONGODB_WIRED_TIGER_JOURNAL_COMPRESSOR=${MONGODB_WIRED_TIGER_JOURNAL_COMPRESSOR}
    - MONGODB_WIRED_TIGER_STATISTICS_LOG_DELAY=${MONGODB_WIRED_TIGER_STATISTICS_LOG_DELAY}

  # mongoexpress:

volumes:
  mongo-data:
  mongo-backup:

networks:
  internal:
  web:
    external: true